baseURL: 'https://yiannis-charalambous.com/'
languageCode: 'en-us'
title: 'Yiannis Charalambous'
uglyurls: true

disableKinds:
  - taxonomy
  - term

sitemap:
  filename: sitemap.xml
  changefreq: monthly
  priority: 0.5

rssLimit: 20