baseURL = "https://yiannis-charalambous.com/"
languageCode = "en-us"
title = "Yiannis Charalambous"
uglyurls = true
theme = "hugo-xmin"

[params]
description = "Welcome to my website, my name is Yiannis Charalambous."
footer = "&copy; [Yiannis](https://yiannis.site) 2018 -- {Year} | [Github](https://github.com/Yiannis128) | [X](https://x.com/Yiannis128)"
# math = true

[taxonomies]
tag = "tags"

[taxonomy]
rssLimit = 20

[taxonomy.sitemap]
filename = "sitemap.xml"
changefreq = "monthly"
priority = 0.5

[markup.goldmark.renderer]
# Enable embedding unsafe HTML into content.
# If this is disabled, you will get a comment instead
# of the HTML "Raw html omitted"
unsafe = true

# This exists because disableKinds has only taxonomy instead of taxonomy and
# term. This is because we display the tags in the articles page directly
# instead of showing them in a separate page.
#ignoreErrors = ["error-disable-taxonomy"]


[markup.highlight]
anchorLineNos = true
codeFences = true
hl_inline = false
lineNos = true
lineNumbersInTable = false # Setting to true causes overflow
# # style = 'algol'
style = 'autumn'
# # style = 'borland'
# # style = 'bw'
# # style = 'emacs'
tabWidth = 4


[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]
